# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Kata\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Kata\Booking\Infrastructure\Ui\Rest\:
        resource: '../src/Booking/Infrastructure/Ui/Rest/'
        tags: [ 'controller.service_arguments' ]


    #INSIGHTS CALCULATOR
    kata.booking.calculators.profit_per_night_calculator:
        class: Kata\Booking\Domain\Insights\Calculator\ProfitPerNightCalculator

    kata.booking.calculators.maximize_total_profits_calculator:
        class: Kata\Booking\Domain\Insights\Calculator\MaximizeTotalProfitsCalculator

    Kata\Booking\Domain\Insights\Calculator\InsightCalculator $profitPerNightCalculator: '@kata.booking.calculators.profit_per_night_calculator'
    Kata\Booking\Domain\Insights\Calculator\InsightCalculator $maximizeTotalProfitsCalculator: '@kata.booking.calculators.maximize_total_profits_calculator'

    #INSIGHTS CALCULATOR PIPES
    kata.booking.pipes.average_pipe:
        class: Kata\Booking\Domain\Insights\Pipes\AveragePipe
    kata.booking.pipes.max_profit_per_night_pipe:
        class: Kata\Booking\Domain\Insights\Pipes\MaxProfitPerNightPipe
    kata.booking.pipes.min_profit_per_night_pipe:
        class: Kata\Booking\Domain\Insights\Pipes\MinProfitPerNightPipe
    kata.booking.pipes.calculate_profit_per_night_pipe:
        class: Kata\Booking\Domain\Insights\Pipes\CalculateProfitPerNightPipe

    kata.booking.pipes.clean_overlaps_pipe:
        class: Kata\Booking\Domain\Insights\Pipes\CleanOverlapsPipe
    kata.booking.pipes.search_all_combinations_pipe:
        class: Kata\Booking\Domain\Insights\Pipes\SearchAllCombinationsPipe

    Kata\Booking\Domain\Insights\Pipes\Pipe $averagePipe: '@kata.booking.pipes.average_pipe'
    Kata\Booking\Domain\Insights\Pipes\Pipe $maxProfitPerNightPipe: '@kata.booking.pipes.max_profit_per_night_pipe'
    Kata\Booking\Domain\Insights\Pipes\Pipe $minProfitPerNightPipe: '@kata.booking.pipes.min_profit_per_night_pipe'
    Kata\Booking\Domain\Insights\Pipes\Pipe $calculateProfitPerNightPipe: '@kata.booking.pipes.calculate_profit_per_night_pipe'
    Kata\Booking\Domain\Insights\Pipes\Pipe $cleanOverlapsPipe: '@kata.booking.pipes.clean_overlaps_pipe'
    Kata\Booking\Domain\Insights\Pipes\Pipe $searchAllCombinationsPipe: '@kata.booking.pipes.search_all_combinations_pipe'
